version: '2'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - mysql-data:/var/lib/mysql    #データの永続化のために必要
    ports:
      - "4306:3306"

  app:
    tty: true          #コンテナ上でbinding.pryするために必要
    stdin_open: true   #コンテナ上でbinding.pryするために必要
    build: .
    command: bundle exec puma -C config/puma.rb
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/rug-match    #ローカルのディレクトリをコンテナ上にマウント
      - public-data:/rug-match/public
      - tmp-data:/rug-match/tmp
      - log-data:/rug-match/log
      - bundle:/usr/local/bundle    #bundle installした後buildし直さなくてよくなる
    # ports:
    #   - "3000:3000"
    depends_on:
      - db

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/rug-match/public
      - tmp-data:/rug-match/tmp
    ports:
      - 80:80
    depends_on:
      - app
  

volumes:
  public-data:
  tmp-data:
  mysql-data:
  log-data:  
  bundle:      #bundle installした後buildし直さなくてよくなる