Category.create(category: '初心者歓迎')
Category.create(category: '経験者募集')
Category.create(category: 'FW募集')
Category.create(category: 'BK募集')
Category.create(category: 'マネージャー募集')
Category.create(category: '実績あり')